analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    avoid_dynamic_calls: ignore
    one_member_abstracts: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
